document.write('<center>'); 
document.write('<h1><u><i>Magical Grill</i></u></h1>'); 
document.write('<nav>'); 
document.write('<h2>');
document.write('&#9733 <a href="/index.html">Home</a> &#9733; '); 
document.write('<a href="/aboutme.html">About Me</a> &#9733; '); 
document.write('<a href="/archives.html">Archive</a> &#9733; '); 
document.write('</h2>'); 
document.write('</nav>'); 
document.write('</center>'); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write('');
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write('');
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 

