document.write('<center>');
document.write('<p><img src="/DoYouLikeKissingGrills.png" width="75%" height="75%" alt=""></p>'); 
document.write('<p><img src="/tape.png" width="120" height="10" alt=""></p>'); 
document.write('<font size="+1"><b><i>Find Me On</i></b></font>'); 
document.write('<br>'); 
document.write('<br>'); 
document.write('<a href="https://anilist.co/user/LiteralGrill/">'); 
document.write('<img src="/AniList%20Button.jpg" alt="AniList">'); 
document.write('</a>'); 
document.write('<a href="https://bsky.app/profile/literalgrill.com">'); 
document.write('<img src="/BlueskyButton.png" alt="Bluesky">'); 
document.write('</a>'); 
document.write('<a href="https://sakurajima.moe/@literalgrill">'); 
document.write('<img src="/mastodon_button_1.gif" alt="Mastodon">'); 
document.write('</a>'); 
document.write('<a href="https://live.literalgrill.com/">'); 
document.write('<img src="/ocbutton.png" alt="Owncast">'); 
document.write('</a>'); 
document.write('<a href="https://share.tube/a/literalgrill/video-channels">'); 
document.write('<img src="/PeerTube.jpg" alt="PeerTube">'); 
document.write('</a>'); 
document.write('<a href="https://archive.org/details/@literalgrill/uploads">'); 
document.write('<img src="/internetarchive.gif" alt="Internet Archive">'); 
document.write('</a>'); 
document.write('<p><img src="/xtape.png" width="120" height="30" alt=""></p>'); 
document.write(' <font size="+1"><b><i>Bylines For</i></b></font>'); 
document.write('<br>'); 
document.write('<br>'); 
document.write('<a href="https://www.animeherald.com/author/bcapps/">'); 
document.write('<img src="/Anime%20Herald%20Button.jpg" alt="Anime Herald">'); 
document.write('</a>'); 
document.write('<a href="https://www.animefeminist.com/author/borealiscapps/">'); 
document.write('<img src="/AniFem2.jpg" alt="Anime Feminist">'); 
document.write('</a>'); 
document.write('<a href="https://yattatachi.com/author/literalgrill">'); 
document.write('<img src="/Yatta-Tachi-88x31-Banner.png" alt="Yatta Tachi">'); 
document.write('</a>'); 
document.write('<p><img src="/xtape.png" width="120" height="30" alt=""></p>'); 
document.write('<font size="+1"><b><i>I Also Love</i></b></font>'); 
document.write('<br>'); 
document.write('<br>'); 
document.write('<a href="https://spacevixen.neocities.org/">');
document.write('<img src="/spacevixen.jpg" width="88" height="31" alt="Space Vixen">'); 
document.write('</a>'); 
document.write('<a href="https://letsfindpokemon-found.neocities.org/">'); 
document.write('<img src="https://letsfindpokemon-found.neocities.org/img/button.png" alt="Lets Find Pokemon! FOUND">'); 
document.write('</a>'); 
document.write('<a href="https://elucidatedvoyyd.neocities.org/rp-home">'); 
document.write('<img src="/roboponiceberg.gif" alt="Robopon Iceberg">'); 
document.write('</a>'); 
document.write('<a href="https://ikewise.neocities.org/">'); 
document.write('<img src="/ikewise_button_green.gif" alt="Ikewise Online">'); 
document.write('</a>'); 
document.write('<a href="https://mayazimmerman.neocities.org/">'); 
document.write('<img src="/maya.gif" alt="Maya "Easy Fantastic Fox Peazy Zimmerman">'); 
document.write('</a>'); 
document.write('<a href="https://lezliz.com/">'); 
document.write('<img src="/LezLiz.png" alt="LezLiz">'); 
document.write('</a>'); 
document.write('<a href="http://spat-harmony.byethost16.com/?i=1">'); 
document.write('<img src="/shhb.png" alt="Spat & Harmony Heartbreak">'); 
document.write('</a>'); 
document.write('<a href="https://osgpod.com/">'); 
document.write('<img src="/OSG.png" alt="On The Shoulders Of Giants Podcast">'); 
document.write('</a>'); 
document.write('<a href="https://princess.software/">'); 
document.write('<img src="/lovewins.png" alt="Princess Graces Lair">'); 
document.write('</a>'); 
document.write('<a href="https://www.xenaville.com/index.html">');
document.write('<img src="/xenaville.gif" width="88" height="31" alt="Xenaville">'); 
document.write('</a>'); 
document.write('<a href="https://furby-junkie.neocities.org/home">');
document.write('<img src="/FurbyJunky.gif" width="88" height="31" alt="Furby Junky">'); 
document.write('</a>'); 
document.write('<a href="https://eriis.gay/">');
document.write('<img src="/eriisgay.png" width="88" height="31" alt="Eri Is Gay">'); 
document.write('</a>'); 
document.write('<a href="https://symtrkl.gay/">');
document.write('<img src="/SymTrkl.png" width="88" height="31" alt="SymTrkl Dot Gay">'); 
document.write('</a>'); 
document.write('<a href="https://xaselgio.net/">');
document.write('<img src="/Xaselgio.gif" width="88" height="31" alt="Indigos Den">'); 
document.write('</a>'); 
document.write('<a href="https://grat.gay/">');
document.write('<img src="/grat10_gay_badge_smol.png" width="88" height="31" alt="Grat.Gay">'); 
document.write('</a>'); 
document.write('<p><img src="/xtape.png" width="120" height="30" alt=""></p>'); 
document.write('<font size="+1"><b><i>Fansubs &#9829;</i></b></font>'); 
document.write('<br>');
document.write('<br>'); 
document.write('<a href="https://www.hamhamparadise.com/m/">'); 
document.write('<img src="/hhp.gif" width="88" height="31" alt="Ham-Ham-Paradise">'); 
document.write('</a>'); 
document.write('<a href="https://southwindsubs.wordpress.com/">'); 
document.write('<img src="/banner-sws-fables.jpg" width="88" height="31" alt="South Wind Subs">'); 
document.write('</a>'); 
document.write('<a href="https://oldcastle.moe/">'); 
document.write('<img src="/old-castle-banner.png" width="88" height="31" alt="Old Castle Fansub Group">'); 
document.write('</a>'); 
document.write('<a href="https://senshifansubs.wordpress.com/">'); 
document.write('<img src="https://senshifansubs.wordpress.com/wp-content/uploads/2023/01/2023-link-88x31-1.gif" alt="Senshi Fansubs">'); 
document.write('</a>'); 
document.write('<a href="http://www.fansubs.ca/">'); 
document.write('<img src="https://senshifansubs.wordpress.com/wp-content/uploads/2013/02/fansub-ca-hime-sharpened.gif" alt="Fansubs.ca">'); 
document.write('</a>'); 
document.write('<a href="https://seigyokusubs.wordpress.com/">'); 
document.write('<img src="/SeigyokuButton.png" alt="Seigyoku">'); 
document.write('</a>'); 
document.write('<a href="http://www.live-evil.org/">');
document.write('<img src="/liveevil.png" alt="Live Evil">'); 
document.write('</a>'); 
document.write('<p><img src="/tape.png" width="120" height="10" alt=""></p>'); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write('');
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write('');
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write('');
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 


